version: '3.8'

services:
  lnurl_server:
    build:
      context: ./lnurl_server
      dockerfile: Dockerfile
    
    environment:
      - NODE_BASE_URL=http://nwc_node:3000
      - LN_ADDRESS_DOMAIN=${LN_ADDRESS_DOMAIN:-localhost:8000}
      - LN_USERNAME=${LN_USERNAME:-nwc}
    depends_on:
      - nwc_node

  nwc_node:
    build:
      context: ./nwc_node
      dockerfile: Dockerfile
    
    environment:
      - NWC_CONNECTION_STRING=${NWC_CONNECTION_STRING}

networks:
  default:
    name: nwc-proxy-network