name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push lnurl_server
      uses: docker/build-push-action@v4
      with:
        context: ./lnurl_server
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/lnurl_server:latest

    - name: Build and push nwc_node
      uses: docker/build-push-action@v4
      with:
        context: ./nwc_node
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/nwc_node:latest